# Generated by Django 3.2.3 on 2021-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posting/'),
        ),
    ]
